---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubearmor-operator-v1.0.1
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kubearmor-operator-v1.0.1
      sourceRef:
        kind: HelmRepository
        name: kubearmor.github.io/charts
        namespace: ${releaseNamespace}
      version: v1.0.1
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: yes
  upgrade:
    remediation:
      retries: 30
  releaseName: kubearmor
  valuesFrom:
    - kind: configMap
      name: kubearmor-1.0.3-defaults
  targetNamespace: ${releaseNamespace}
