---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubearmor-operator-v1.0.3
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kubearmor-operator-v1.0.3
      sourceRef:
        kind: HelmRepository
        name: kubearmor.github.io/charts
        namespace: ${workspaceNamespace}
      version: 1.0.3
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: kubearmor-operator-v1.0.3
  valuesFrom:
    - kind: ConfigMap
      name: kubearmor-1.0.3-defaults
  targetNamespace: ${releaseNamespace}
